/* Escolhendo um Banco de Dados */
USE
	COMERCIO_OLTP
GO


/* Inserindo Dados na Tabela Fornecedor */
INSERT INTO FORNECEDOR VALUES('EDITORA LELIVROS')
INSERT INTO FORNECEDOR VALUES('EDITORA MUNDO FANTASIA')
INSERT INTO FORNECEDOR VALUES('EDITORA AMAZONIA')
INSERT INTO FORNECEDOR VALUES('STUDIOS HB')
INSERT INTO FORNECEDOR VALUES('STUDIOS HOLLYWOOD')
INSERT INTO FORNECEDOR VALUES('STUDIOS CALIFORNIA')
INSERT INTO FORNECEDOR VALUES('EM SPORTS')
INSERT INTO FORNECEDOR VALUES('BILLZAR GAMES')
INSERT INTO FORNECEDOR VALUES('BRAZUCA JOGOS')
INSERT INTO FORNECEDOR VALUES('JOGAR GAMES')
INSERT INTO FORNECEDOR VALUES('MOTOROLA') --
INSERT INTO FORNECEDOR VALUES('NOKIA') --
INSERT INTO FORNECEDOR VALUES('SAMSUNG') --
INSERT INTO FORNECEDOR VALUES('LG') --
INSERT INTO FORNECEDOR VALUES('DREAMC') --
INSERT INTO FORNECEDOR VALUES('GFORCE') --
INSERT INTO FORNECEDOR VALUES('APPLE') --
INSERT INTO FORNECEDOR VALUES('SONY') --
INSERT INTO FORNECEDOR VALUES('WALLITA') --
INSERT INTO FORNECEDOR VALUES('ARNO') --
INSERT INTO FORNECEDOR VALUES('MULTILASER') --
INSERT INTO FORNECEDOR VALUES('MICROSOFT') --
INSERT INTO FORNECEDOR VALUES('ACER') --
INSERT INTO FORNECEDOR VALUES('VISION') --
INSERT INTO FORNECEDOR VALUES('PHILIPS')
INSERT INTO FORNECEDOR VALUES('SANDISK') --
INSERT INTO FORNECEDOR VALUES('BRASTEMP') --
INSERT INTO FORNECEDOR VALUES('GANCA') --
INSERT INTO FORNECEDOR VALUES('BRITANIA') --
INSERT INTO FORNECEDOR VALUES('MOVEIS VAREJÃO')
INSERT INTO FORNECEDOR VALUES('BRASIL MADEIRAS')
INSERT INTO FORNECEDOR VALUES('LINHAS AÉREAS BRAZUCA')
INSERT INTO FORNECEDOR VALUES('LINHAS BRASIL EXPRESS')
INSERT INTO FORNECEDOR VALUES('LINHAS LATINAS DE AVIÕES')
INSERT INTO FORNECEDOR VALUES('LINHAS INTERNACIONAIS EURO')
INSERT INTO FORNECEDOR VALUES('AMERICA LINES EXPRESS')
INSERT INTO FORNECEDOR VALUES('LENOVO')
INSERT INTO FORNECEDOR VALUES('CCE')
INSERT INTO FORNECEDOR VALUES('PANASONIC')
INSERT INTO FORNECEDOR VALUES('GENIUS')
INSERT INTO FORNECEDOR VALUES('HP')
GO