/* Escolhendo um Banco de Dados */
USE 
	COMERCIO_OLTP
GO


/* Inserindo Dados na Tabela Vendedor */
INSERT INTO VENDEDOR VALUES('EDUARDO SANTOS','M','ESANTOS.MANAGER@TERA.COM',NULL)
INSERT INTO VENDEDOR VALUES('RENATA MONTEIRO','F','RMONT@TERA.COM',1)
INSERT INTO VENDEDOR VALUES('JOAO NUNES','M','JNUNES@TERA.COM',1)
INSERT INTO VENDEDOR VALUES('CLARA MAFRA','F','CMAFRA@TERA.COM',1)
INSERT INTO VENDEDOR VALUES('GERALDO FRANCISCO','M','GFRANCISCO@TERA.COM',1)
INSERT INTO VENDEDOR VALUES('RODRIGO BIO','M','RBIO@TERA.COM',1)
INSERT INTO VENDEDOR VALUES('SERGIO AGUDO','M','SAGUDO@TERA.COM',1)
INSERT INTO VENDEDOR VALUES('PILAR SANCHES','F','PSANCHES@TERA.COM',1)
INSERT INTO VENDEDOR VALUES('MARCELO WITEMBERG','M','MWITEMBERG@TERA.COM',1)
INSERT INTO VENDEDOR VALUES('LILIAN SALINAS','F','LSALINAS@TERA.COM',NULL)
INSERT INTO VENDEDOR VALUES('RAFAELA LIMA','F','RLIMA@TERA.COM',10)
INSERT INTO VENDEDOR VALUES('CELIA TAVARES','F','CTAVARES@TERA.COM',10)
INSERT INTO VENDEDOR VALUES('HERMES MACEDO','M','HMACEDO@TERA.COM',10)
INSERT INTO VENDEDOR VALUES('SILVIO BAHIANA','M','SBAHIANA@TERA.COM',10)
INSERT INTO VENDEDOR VALUES('DEBORA ALMEIDA','F','DALMEIDA@TERA.COM',10)
INSERT INTO VENDEDOR VALUES('DAVID BORGES','M','DBORGES@TERA.COM',NULL)
INSERT INTO VENDEDOR VALUES('TERESA CRISTINA','F','TCRISTINA@TERA.COM',15)
INSERT INTO VENDEDOR VALUES('RODRIGO MARQUES','M','EMACHADO@TERA.COM',15)
INSERT INTO VENDEDOR VALUES('CARLOS SENRA','M','CSENRA@TERA.COM',16)
INSERT INTO VENDEDOR VALUES('FABIO AUGUSTO','M','FAUGUSTO@TERA.COM',16)
INSERT INTO VENDEDOR VALUES('WALLACE MOREIRA','M','WMOREIRA@TERA.COM',16)
INSERT INTO VENDEDOR VALUES('RENE CHIARI','M','RCHIARI@TERA.COM',16)
INSERT INTO VENDEDOR VALUES('ANTONIO JESUS','M','AJESUS@TERA.COM',16)
INSERT INTO VENDEDOR VALUES('PEDRO NUNES','M','PNUNES@TERA.COM',16)
GO